import Foundation

// MARK: - Game Object Types

enum ObjectKind {
    case unit
    case infantry
    case structure
}

enum Mission: String {
    // Core missions (VC mission.h)
    case sleep = "Sleep"
    case attack = "Attack"
    case move = "Move"
    case retreat = "Retreat"
    case guard_ = "Guard"
    case sticky = "Sticky"         // Guard without auto-target
    case enter = "Enter"
    case capture = "Capture"
    case harvest = "Harvest"
    case guardArea = "Guard Area"
    case return_ = "Return"
    case stop = "Stop"
    case ambush = "Ambush"
    case hunt = "Hunt"
    case timedHunt = "Timed Hunt"
    case unload = "Unload"
    case repair = "Repair"
    case missile = "Missile"
    case construction = "Construction"
    case deconstruction = "Deconstruction"
    case selling = "Selling"

    static func from(_ string: String) -> Mission {
        switch string.lowercased() {
        case "guard":          return .guard_
        case "move":           return .move
        case "stop":           return .stop
        case "sleep":          return .sleep
        case "attack":         return .attack
        case "harvest":        return .harvest
        case "hunt":           return .hunt
        case "ambush":         return .ambush
        case "retreat":        return .retreat
        case "enter":          return .enter
        case "capture":        return .capture
        case "guard area":     return .guardArea
        case "return":         return .return_
        case "unload":         return .unload
        case "repair":         return .repair
        case "sticky":         return .sticky
        case "timed hunt":     return .timedHunt
        default:               return .guard_
        }
    }
}

// MARK: - Game Object

/// Unified game object — represents units, infantry, and structures.
/// Type-specific data is resolved once at creation time via cached lookups.
class GameObject {
    let id: Int
    let typeName: String
    var house: House                // Mutable for capture
    let kind: ObjectKind

    // Position in double-pixel coordinates (sub-pixel smooth)
    var worldX: Double
    var worldY: Double
    var prevWorldX: Double          // Previous tick position (for render interpolation)
    var prevWorldY: Double
    var facing: Int                 // 0-255 C&C facing (0=N, 64=E, 128=S, 192=W)
    var turretFacing: Int = 0       // Turret facing for units with turrets
    var strength: Int               // Hit points

    // Mission state (VC MissionClass)
    var mission: Mission
    var missionQueue: Mission? = nil         // Queued next mission
    var suspendedMission: Mission? = nil     // Saved mission for resume
    var missionStatus: Int = 0               // Sub-state within current mission
    var isSelected: Bool = false

    // Movement (VC FootClass)
    var moveTargetX: Double? = nil
    var moveTargetY: Double? = nil
    var speed: Double               // Pixels per tick
    var movePath: [(cellX: Int, cellY: Int)] = []
    var navTargetId: Int? = nil     // Navigation target object ID
    var group: Int = -1             // Control group (0-9, -1 = none)

    // Combat (VC TechnoClass)
    var attackTarget: Int? = nil    // Target object ID
    var suspendedTarget: Int? = nil // Saved target (VC SuspendedTarCom)
    var reloadTimer: Int = 0
    var lastFireTick: Int = 0       // Tick when unit last fired (for muzzle flash)
    var lastDamagedTick: Int = 0    // Tick when unit last took damage (for damage flash)
    var ammo: Int = -1              // -1 = unlimited

    // Harvesting (units only)
    var tiberiumLoad: Int = 0

    // Infantry-specific (VC InfantryClass)
    var subCell: Int
    var fear: UInt8 = 0             // 0-255: 0=fearless, 200=panic
    var isProne: Bool = false       // Crawling/prone

    // Building-specific (VC BuildingClass)
    var isRepairing: Bool = false
    var lastWhoHurtMe: House? = nil // For kill credit
    var powerOutput: Int = 0        // Power generated by this building
    var powerDrain: Int = 0         // Power consumed by this building

    // Aircraft-specific (VC AircraftClass)
    var isAircraft: Bool = false    // True if this is an aircraft object
    var altitude: Int = 0           // 0=ground, 24=flight level
    var isLanding: Bool = false     // In landing sequence
    var isTakingOff: Bool = false   // In takeoff sequence

    // Flags (VC TechnoClass/ObjectClass)
    var isInLimbo: Bool = false     // In transport or off-map
    var isTethered: Bool = false    // Loosely attached to unit (docking)

    // Trigger
    var triggerName: String? = nil  // Attached trigger ID

    // Computed cell position
    var cellX: Int { Int(worldX) / 24 }
    var cellY: Int { Int(worldY) / 24 }
    var cell: Int { cellY * 64 + cellX }

    // MARK: - Cached Type Data

    // These are resolved once at creation time for performance
    private(set) var cachedPrimaryWeapon: WeaponType? = nil
    private(set) var cachedSecondaryWeapon: WeaponType? = nil
    private(set) var cachedArmor: ArmorType = .none
    private(set) var cachedSightRange: Int = 3
    private(set) var cachedMaxStrength: Int = 100
    private(set) var cachedCost: Int = 0
    private(set) var cachedHasTurret: Bool = false
    private(set) var cachedSpeedType: SpeedType = .foot

    /// Resolve type data from tables and cache it
    private func cacheTypeData() {
        let upper = typeName.uppercased()
        switch kind {
        case .unit:
            // Check if this is an aircraft type
            if let at = AircraftType.from(iniName: upper), let data = aircraftTypeDataTable[at] {
                cachedPrimaryWeapon = data.primaryWeapon
                cachedSecondaryWeapon = data.secondaryWeapon
                cachedArmor = data.armor
                cachedSightRange = data.sightRange
                cachedMaxStrength = data.strength
                cachedCost = data.cost
                cachedHasTurret = false
                cachedSpeedType = .winged
                ammo = data.maxAmmo
            } else if let ut = UnitType.from(iniName: upper), let data = unitTypeDataTable[ut] {
                cachedPrimaryWeapon = data.primaryWeapon
                cachedSecondaryWeapon = data.secondaryWeapon
                cachedArmor = data.armor
                cachedSightRange = data.sightRange
                cachedMaxStrength = data.strength
                cachedCost = data.cost
                cachedHasTurret = data.hasTurret
                cachedSpeedType = data.speed
                ammo = data.ammo
            }
        case .infantry:
            if let it = InfantryType.from(iniName: upper), let data = infantryTypeDataTable[it] {
                cachedPrimaryWeapon = data.primaryWeapon
                cachedSecondaryWeapon = data.secondaryWeapon
                cachedArmor = data.armor
                cachedSightRange = data.sightRange
                cachedMaxStrength = data.strength
                cachedCost = data.cost
                cachedSpeedType = .foot
            }
        case .structure:
            if let st = StructType.from(iniName: upper), let data = buildingTypeDataTable[st] {
                cachedPrimaryWeapon = data.primaryWeapon
                cachedSecondaryWeapon = data.secondaryWeapon
                cachedArmor = data.armor
                cachedSightRange = data.sightRange
                cachedMaxStrength = data.strength
                cachedCost = data.cost
                powerOutput = data.powerProduction
                powerDrain = data.powerDrain
            }
        }
    }

    // MARK: - Public Type Data Accessors (use cached values)

    var primaryWeapon: WeaponType? { cachedPrimaryWeapon }
    var secondaryWeapon: WeaponType? { cachedSecondaryWeapon }
    var armorType: ArmorType { cachedArmor }
    var sightRange: Int { cachedSightRange }
    var maxStrength: Int { cachedMaxStrength }
    var cost: Int { cachedCost }
    var hasTurret: Bool { cachedHasTurret }
    var speedType: SpeedType { cachedSpeedType }

    /// Damage ratio as fraction (1.0 = full health, 0.0 = dead)
    var healthFraction: Double {
        guard cachedMaxStrength > 0 else { return 0.0 }
        return Double(strength) / Double(cachedMaxStrength)
    }

    /// True if this object is armed (has a weapon)
    var isArmed: Bool { cachedPrimaryWeapon != nil }

    /// True if this object can move
    var isMobile: Bool { kind != .structure }

    init(id: Int, typeName: String, house: House, kind: ObjectKind,
         worldX: Double, worldY: Double, facing: Int, strength: Int,
         mission: Mission, speed: Double, subCell: Int = 0) {
        self.id = id
        self.typeName = typeName
        self.house = house
        self.kind = kind
        self.worldX = worldX
        self.worldY = worldY
        self.prevWorldX = worldX
        self.prevWorldY = worldY
        self.facing = facing
        self.turretFacing = facing
        self.strength = strength
        self.mission = mission
        self.speed = speed
        self.subCell = subCell
        // Cache type data after all properties are set
        cacheTypeData()
    }
}

// MARK: - Game World

class GameWorld {
    var objects: [GameObject] = []
    var nextObjectId: Int = 0
    var tickCount: Int = 0
    var theater: TheaterType = .temperate
    var mapBounds: MapBounds?
    var occupancy: [Int: Int] = [:]  // cell -> object id occupying it
    var playerHouse: House = .goodGuy
    var map: GameMap = GameMap()

    // Control groups (0-9), each can hold multiple object IDs
    var controlGroups: [[Int]] = Array(repeating: [], count: 10)

    func addObject(_ obj: GameObject) {
        objects.append(obj)
    }

    func allocateId() -> Int {
        let id = nextObjectId
        nextObjectId += 1
        return id
    }

    func selectedObjects() -> [GameObject] {
        objects.filter { $0.isSelected }
    }

    func deselectAll() {
        for obj in objects {
            obj.isSelected = false
        }
    }

    /// Find an object by ID (O(n) scan)
    func findObject(id: Int) -> GameObject? {
        objects.first { $0.id == id }
    }

    /// Get all objects of a specific kind owned by a house
    func objects(ofKind kind: ObjectKind, house: House) -> [GameObject] {
        objects.filter { $0.kind == kind && $0.house == house && $0.strength > 0 }
    }

    /// Count living objects by kind and house
    func countObjects(ofKind kind: ObjectKind, house: House) -> Int {
        objects.count { $0.kind == kind && $0.house == house && $0.strength > 0 }
    }

    /// Total power output for a house
    func totalPower(for house: House) -> Int {
        objects.filter { $0.kind == .structure && $0.house == house && $0.strength > 0 }
            .reduce(0) { $0 + $1.powerOutput }
    }

    /// Total power drain for a house
    func totalDrain(for house: House) -> Int {
        objects.filter { $0.kind == .structure && $0.house == house && $0.strength > 0 }
            .reduce(0) { $0 + $1.powerDrain }
    }

    /// Check if a house has a specific building type
    func hasBuilding(type: String, house: House) -> Bool {
        objects.contains { $0.kind == .structure && $0.house == house &&
            $0.strength > 0 && $0.typeName.caseInsensitiveCompare(type) == .orderedSame }
    }
}

